// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfE88ep8RHMikJaHlZixvWDK-P8hsA4bY',
    appId: '1:346042280759:web:120afb18ce61c1ffbac8b2',
    messagingSenderId: '346042280759',
    projectId: 'firebase-nghia',
    authDomain: 'fir-nghia-8a1ad.firebaseapp.com',
    storageBucket: 'firebase-nghia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgFuZ1D-fJa-4B2mrdJW6aipmn8Y0Rt_c',
    appId: '1:346042280759:android:1d8dfb9f91dabd89bac8b2',
    messagingSenderId: '346042280759',
    projectId: 'firebase-nghia',
    storageBucket: 'firebase-nghia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSY7faAhf2s08GsufAR6i0JRGlJLBa1es',
    appId: '1:346042280759:ios:b099e12b0b1432a0bac8b2',
    messagingSenderId: '346042280759',
    projectId: 'firebase-nghia',
    storageBucket: 'firebase-nghia.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSY7faAhf2s08GsufAR6i0JRGlJLBa1es',
    appId: '1:346042280759:ios:b099e12b0b1432a0bac8b2',
    messagingSenderId: '346042280759',
    projectId: 'firebase-nghia',
    storageBucket: 'firebase-nghia.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfE88ep8RHMikJaHlZixvWDK-P8hsA4bY',
    appId: '1:346042280759:web:62a4552981e4006dbac8b2',
    messagingSenderId: '346042280759',
    projectId: 'firebase-nghia',
    authDomain: 'fir-nghia-8a1ad.firebaseapp.com',
    storageBucket: 'firebase-nghia.appspot.com',
  );
}
